name: up_chuck_flutter
description: Chuck Norris Quotes

publish_to: "none"

version: 1.0.5

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  http: ^0.13.5
  riverpod: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
